<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>javelin</groupId>
    <artifactId>javelin</artifactId>
    <version>1.0.0</version>
    
	<properties>
		<lwjgl.version>3.4.3</lwjgl.version>
		<steamworks4j.version>1.10.0</steamworks4j.version>
		<lwjgl3-awt.version>0.2.3</lwjgl3-awt.version>
		
	    <maven.compiler.source>25</maven.compiler.source>
	    <maven.compiler.target>25</maven.compiler.target>
	    <maven.compiler.release>25</maven.compiler.release>
	    
        <doclint>none</doclint>
        
        <target.platform>linux-x64</target.platform>
        
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	
	<build>
		<sourceDirectory>code/</sourceDirectory>
        <plugins>
    		<plugin>
			    <groupId>org.apache.maven.plugins</groupId>
			    <artifactId>maven-javadoc-plugin</artifactId>
			    <version>3.12.0</version>
			    <configuration>
		            <outputDirectory>doc/</outputDirectory>
			    </configuration>
			</plugin>
			<plugin>
			    <groupId>org.apache.maven.plugins</groupId>
			    <artifactId>maven-jlink-plugin</artifactId>
			    <version>3.2.0</version>
			    <extensions>true</extensions>
			    <configuration>
			        <addModules>
			            <addModule>javelin</addModule>
			        </addModules>
			        <modulePaths>
			            <modulePath>${project.build.directory}/modules/</modulePath>
			            <modulePath>${project.build.directory}/classes/</modulePath>
			            <modulePath>build/jdk/${platform}/jmods/</modulePath>
			        </modulePaths>
			    </configuration>
			</plugin>
			<plugin>
			    <groupId>org.moditect</groupId>
			    <artifactId>moditect-maven-plugin</artifactId>
			    <version>1.0.0.Final</version>
			    <executions>
			        <execution>
			            <id>add-module-infos</id>
			            <phase>generate-resources</phase>
			            <goals><goal>add-module-info</goal></goals>
			            <configuration>
			                <modules>
			                    <module>
			                        <artifact>
									    <groupId>com.code-disaster.steamworks4j</groupId>
									    <artifactId>steamworks4j</artifactId>
									    <version>${steamworks4j.version}</version>
			                        </artifact>
			                        <moduleInfoSource>
			                            module steamworks4j {
			                                exports com.codedisaster.steamworks;
			                            }
			                        </moduleInfoSource>
			                    </module>
			                </modules>
                            <overwriteExistingFiles>true</overwriteExistingFiles>
			            </configuration>
			        </execution>
			    </executions>
			</plugin>
			<plugin>
			    <groupId>org.apache.maven.plugins</groupId>
			    <artifactId>maven-dependency-plugin</artifactId>
			    <version>3.6.1</version>
			    <executions>
			        <execution>
			            <id>unpack-natives</id>
			            <phase>package</phase>
			            <goals><goal>unpack</goal></goals>
			            <configuration>
			                <artifactItems>
			                    <artifactItem>
			                        <groupId>org.lwjgl</groupId>
			                        <artifactId>lwjgl</artifactId>
			                        <version>${lwjgl.version}</version>
			                        <classifier>${lwjgl.natives}</classifier>
			                        <type>jar</type>
			                        <outputDirectory>${project.build.directory}/native/</outputDirectory>
			                        <includes>**/*.so</includes>
			                    </artifactItem>
			                </artifactItems>
			            </configuration>
			        </execution>
			    </executions>
			</plugin>
        </plugins>
    </build>
	<profiles>
		<profile>
			<id>lwjgl-natives-linux-amd64</id>
			<activation>
				<os>
					<family>unix</family>
					<name>linux</name>
					<arch>amd64</arch>
				</os>
			</activation>
			<properties>
				<lwjgl.natives>natives-linux</lwjgl.natives>
			</properties>
		</profile>
		<profile>
			<id>lwjgl-natives-windows-amd64</id>
			<activation>
				<os>
					<family>windows</family>
					<arch>amd64</arch>
				</os>
			</activation>
			<properties>
				<lwjgl.natives>natives-windows</lwjgl.natives>
			</properties>
		</profile>
	</profiles>
	
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.lwjgl</groupId>
				<artifactId>lwjgl-bom</artifactId>
				<version>${lwjgl.version}</version>
				<scope>import</scope>
				<type>pom</type>
			</dependency>
		</dependencies>
	</dependencyManagement>
	
	<dependencies>
		<dependency>
			<groupId>org.lwjgl</groupId>
			<artifactId>lwjgl</artifactId>
		</dependency>
		<dependency>
			<groupId>org.lwjgl</groupId>
			<artifactId>lwjgl</artifactId>
			<classifier>${lwjgl.natives}</classifier>
		</dependency>
	  <dependency>
	    <groupId>com.code-disaster.steamworks4j</groupId>
	    <artifactId>steamworks4j</artifactId>
	    <version>${steamworks4j.version}</version>
	  </dependency>
	</dependencies>
</project>
